---
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  github_document:
    toc: true
    toc_depth: 1
---

# Required Packages
In this project, we will use a number of amazing R packages:

  * `knitr`: to generate pretty tables of date using the `kable()` function.  
  * `tidyverse`: to manipulate data, generate plots (via `ggplot2`), and to use piping/chaining.
  * `rmarkdown`: to knit output files manually using the `render()` function.  
  * `jsonlite`: to pull data from various endpoints of the Covid 19 APIs.
  
```{r setup, include=FALSE, message=FALSE, warning=FALSE}
# Load necessary packages
library(knitr)
library(tidyverse)
library(rmarkdown)
library(jsonlite)
library(httr)
```


```{r 1}
#function that generates a vector of countries and their corresponding Slug name whose data are update daily.

countryList <- function(){
  covid <- GET("https://api.covid19api.com/countries")
  covidDF <- fromJSON(rawToChar(covid$content))
  countryList <- covidDF %>% as_tibble()
  return(countryList)
}

countryList <- countryList()
head(countryList)
```

```{r 2}
#a function to determine the slug name of a country

countrySlugAbbrev <- function(inputCountry){
  if (inputCountry %in% countryList$Country){
      covidData <- GET("https://api.covid19api.com/countries")
      covidDF <- fromJSON(rawToChar(covidData$content))
      dataTibble <- covidDF %>% filter(Country == inputCountry ) %>% as_tibble()
  } else {
    message <- paste("ERROR: Argument for country cannot be found, check spelling.
                     Lastly, use quotation marks in your arguments.")
    stop(message)
  }
  return(dataTibble)
}
  
countrySlugAbbrev("United States of America")
```

```{r 3}
#function to determine the date of the first confirmed covid case of a country
firstCase <- function(countrySlug){
  if (countrySlug %in% countryList$Slug){
      url <- paste0("https://api.covid19api.com/dayone/country/",countrySlug,"/status/confirmed")
      covidData <- GET(url)
      covidDF <- fromJSON(rawToChar(covidData$content))
      dataTibble <- covidDF %>% select(Country, Cases, Status, Date) %>% as_tibble()
  } else {
    message <- paste("ERROR: Argument for country nslug cannot be found, check spelling.
                     Lastly, use quotation marks in your arguments.")
    stop(message)
  }
  return(dataTibble[1,])
}

firstCase("philippines")
```

```{r 4}
#confirmed cumulative cases of a country in a specific range of time
#specific country and specific time, start and end date must be in the format yyyy-mm-dd

casesCountryTime <- function(countrySlug, startDate, endDate){
  if (countrySlug %in% countryList$Slug){
      url <- paste0("https://api.covid19api.com/total/country/",countrySlug,
                    "/status/confirmed?from=",startDate,"T00:00:00Z&to=",endDate,"T00:00:00Z")
      covidData <- GET(url)
      covidDF <- fromJSON(rawToChar(covidData$content))
      dataTibble <- covidDF %>% select(Country, Cases, Status, Date) %>% as_tibble()
  } else {
    message <- paste("ERROR: Argument for country slug may not be found, check the list of 
                      countries with its corresponding slug name. Start and end dates are might
                      have formatted incorrectly. Lastly, use quotation marks in your arguments.")
    stop(message)
  }
  return(dataTibble)
}

philSept <- casesCountryTime("philippines","2021-09-01", "2021-09-30")
head(philSept)

```


```{r 5,warning=F, message=F}
#function to get data of a country's cumulative cases of the following: Confirmed, Deaths, Recovered and Active.

variableCountryTime <- function(countrySlug, startDate, endDate, type){
  if (countrySlug %in% countryList$Slug){
      url <- paste0("https://api.covid19api.com/country/",countrySlug,
                    "?from=",startDate,"T00:00:00Z&to=",endDate,"T00:00:00Z")
      covidData <- GET(url)
      covidDF <- fromJSON(rawToChar(covidData$content))
      dataTibble <- covidDF %>% select(Country, type, Date) %>% as_tibble()
  } else {
    message <- paste("ERROR: Argument for country slug may not be found, check the list of 
                      countries with its corresponding slug name. Start and end dates 
                      are might have formatted incorrectly. Lastly, use quotation marks in your arguments.")
    stop(message)
  }
  return(dataTibble)
}

philSept <- variableCountryTime("philippines","2021-09-26", "2021-10-02", "Deaths")
philSept
```

```{r 6}
#get latest results of five countries to compare
compareCountries <- function(country1, country2, country3, country4, country5){
  covid <- GET("https://api.covid19api.com/summary")
  covidDF <- fromJSON(rawToChar(covid$content))
  data <- covidDF$Countries %>% as_tibble()
  countries <- c(country1, country2, country3, country4, country5)
  finalData <- data.frame(matrix(ncol=6,nrow=0))
  names(finalData) <- c("Country","NewConfirmed","TotalConfirmed","NewDeaths","TotalDeaths","Date")
  for (country in countries){
    if (country %in% data$Country){
      finalData[nrow(finalData)+1, ] <- data %>% filter(data$Country == country) %>% 
        select(c(Country,NewConfirmed,TotalConfirmed,NewDeaths,TotalDeaths,Date))
    }
    else{
      message <- paste("ERROR: Check spelling of first country or use quotation marks.")
      stop(message)
    }
  }
  return(finalData %>% as_tibble())
}  
  
compareCountries("Philippines","China", "Mexico", "United States of America", "Canada")

```


```{r 7}
#function to generate all data (daily new cases, deaths, active and recoveries) of a particular country since the start of the pandemic

countryData <- function(countrySlug){
  if (countrySlug %in% countryList$Slug){
      url <- paste0("https://api.covid19api.com/total/country/",countrySlug)
      covidData <- GET(url)
      covidDF <- fromJSON(rawToChar(covidData$content))
      dataTibble <- covidDF %>% as_tibble()
  } else {
    message <- paste("ERROR: Argument for country slug is not found.
                     Check the list of countries with its corresponding slug name
                     and use quotation marks.")
    stop(message)
  }
  return(dataTibble)
}

#now we can use the function to generate some data from five sample countries
covidUS <- countryData("united-states")
tail(covidUS)
```
